queryID	16
email	juhur@umich.edu
userName	Junguk Hur
queryName	ALS INF
count	168
fileNameBase	Query_16__juhur
ignoreName	
excludeSymbol	
includeSymbol	
useLengthOption	1
wordLengthThreshold	6
phenotypeOnlyFilter	1
queryString	 
SciMinerServerURL	http://localhost:8888/
InstitutionCheck	1
useScoreThreshold	1
scoreThreshold	0.1
miningMode	SciMinerMining
speciesExtension	speciesExtension
